### ISSUE TITLE
ccminer default config file not updated for decred

### ISSUE THREAD

**Issue by chappjc** [decred/decred-binaries#11]
The ccminer.conf in the win64 zip is not updated for Decred, still specifying vanilla algo and old vnl.suprnova.cc pool url, etc.  Needs automatic build script that can be called by [minersbuild.sh](https://github.com/decred/decred-binaries/blob/master/minersbuild.sh).

**Comment by jolan** [comment]
I agree that a more reasonable/usable example config should be included that contains a list of pools that support Decred or something like that.   Been trying to limit our packaging changes and even the official release has some discrepancies between the contents of x64 and x86 directories.

I haven't investigated automatic building on Windows at all yet.  It should be possible using something like MSBuild.

Will leave this open as a reminder for the next release.

**Comment by jolan** [comment]
The likelihood of another ccminer build is pretty low now that CUDA support has landed in gominer so I'm going to close this.
