### ISSUE TITLE
Purchaseonly ticket buyer wallet option

### ISSUE THREAD

**Issue by onyx4** [decred/decred-binaries#112]
Problem:

When doing solo mining, even when using a dual wallet hot/cold with a voting-only wallet, the hot wallet which does the ticket purchase has to remained unlocked and is at risk of moving funds if someone is able to access the system with login privileges.      

The same problem would apply for someone doing mining with a pool and wants to use the automated ticket buyer.  The remaining balance in the wallet remains at risk even if the majority of the funds are held in tickets, or when proceeds for voting are returned to the wallet and the ticket price is too high, the funds would sit in the wallet for a period of time being at risk of being transferred out.

Solution:

dcrwallet should have an option to start the process in "ticket-purchase-only" mode where even if the wallet is unlocked it can only be used to buy tickets or receive funds but funds cannot be transferred out without unlocking again in "full" mode or restarting the process. 

Workaround:

The only current safe option is to have the ticket buying wallet be cold wallet but it cannot automatically purchase tickets in this case and requires a manual process every few days to unlock the wallet for purchasing tickets.

**Comment by onyx4** [comment]
I realized this should have been opened under dcrwallet, can you guys move it or I should re-open a new issue under dcrwallet?

**Comment by JoeGruffins** [comment]
You should close and make a new issue in the correct repository.

Are you sure you mean mining and not staking?

**Comment by onyx4** [comment]
Yes sorry I meant staking.   I closed this one and opened the new issue:  https://github.com/decred/dcrwallet/issues/1546
