### ISSUE TITLE
Cannot verify file for v1.5.1

### ISSUE THREAD

**Issue by lbkvu** [decred/decred-binaries#125]
I tried to verify the setup file for Mac OS but got the following error:
```
gpg --verify decrediton-v1.5.1-manifest.txt.asc decrediton-v1.5.1.dmg
gpg: Signature made Thu Jan 30 07:38:58 2020 JST
gpg:                using RSA key F516ADB7A069852C7C28A02D6D897EDF518A031D
gpg: BAD signature from "Decred Release <release@decred.org>" [unknown]
```

Steps to reproduce:
1. Download `decrediton-v1.5.1.dmg` and `decrediton-v1.5.1-manifest.txt.asc` from https://github.com/decred/decred-binaries/releases/tag/v1.5.1
2. Run the above command

**Comment by jrick** [comment]
The signature is for the decrediton-v1.5.1-manifest.txt file, not the dmg itself.  The manifest contains SHA256 digests committing to the authenticity of the files for all platforms.
