### ISSUE TITLE
1.6RC4 (linux/kubuntu) Is mixer running or not?

### ISSUE THREAD

**Issue by hermanlim** [decred/decred-binaries#132]
Had mixer running. The circular mixing icon is spinning. Everything just works. ;)

Thinking of shutting down decrediton to do some computer updates.

However, turning "off" the mixer in the privacy panel results in the notification that the mixer is not running, however the circular mixing icon remains spinning. Hovering over the spinning icon reveals the tool tip that the mixer is still running, which is conflicting information.

Is the mixer running or not? Is it safe to close decrediton?

**Comment by jrick** [comment]
Please open issues on the respective projects' issue trackers (dcrd, dcrwallet, decrediton, dcrdex, etc.).  This issue tracker isn't as well watched by all developers who need to see this.
