### ISSUE TITLE
wallet cannol be opened after upgrade

### ISSUE THREAD

**Issue by geenius55** [decred/decred-binaries#21]
Hi, I cannot open wallet after upgrade. I have this error.

[img]http://i.imgur.com/jdv1OqE.jpg[/img]

**Comment by geenius55** [comment]
![decred wallet 051](https://cloud.githubusercontent.com/assets/22777386/19286205/19b930b4-8ffd-11e6-9f9a-74245fb6243e.png)

**Comment by chappjc** [comment]
Same error message was reported in the forum: https://forum.decred.org/threads/dd-17-v0-5-0-10-10-16.4041/#post-22243
Resolution had to do with Windows Firewall.

**Comment by geenius55** [comment]
I have completely switched off the firewall , but still the same problem. :(

**Comment by raedah** [comment]
@geenius55 did you try the 0.5.1 release. it fixes a bug that was only triggered by wallets created way back before 0.1.2.

**Comment by geenius55** [comment]
No I had 0.4.0 before. But I replaced maually all files in 0.4.0 to 0.5.0 (and later to 0.5.1) and then restarted computer. After the restart it shows that message. 0.5.1 has the same problem. Also if I replace files back to 0.4.0 it is still the same problem.

**Comment by jcvernaleo** [comment]
This is a Paymetheus error, not a build error.  If it is still a problem, please reopen it in decred/Paymetheus.
