### ISSUE TITLE
validate v0.8.2 release

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-binaries#30]
The upcoming v0.8.2 release needs some sanity checking/validating.  Tests needed:
- [x] Paymetheus win7
- [x] Paymetheus win10
- [x] decrediton osx
- [x] decrediton linux
- [x] dcrinstall any system
- [x] cmd line tools any system.

Please comment with what you tested (linux distro, etc).

**Comment by jrick** [comment]
msi running fine on win10 and I verified the cli tools are version 0.8.2

**Comment by jcvernaleo** [comment]
win7 paymetheus seems okay for me.

**Comment by jrick** [comment]
Decrediton on Fedora also looking fine, also verified the correct versions there.

**Comment by jolan** [comment]
dcrinstall upgrade/clean install worked fine on linux-amd64.

dcrd is working fine for mining on testnet.

**Comment by jcvernaleo** [comment]
And osx seems ok.
