### ISSUE TITLE
CUDA runtime libraries should be packaged with binaries

### ISSUE THREAD

**Issue by chappjc** [decred/decred-binaries#37]
These shared libraries are required to run gominer (or anything using the CUDA runtime).  They are only available with the CUDA toolkit, not the drivers, as they are intended for packaging with the binaries.  They are redistrubutable royalty-free.

See Section 1.8 of the EULA : http://docs.nvidia.com/cuda/eula/index.html#attachment-a

The relevant part:

> Component : CUDA Runtime
> Windows : cudart.dll, cudart_static.lib, cudadevrt.lib
> Mac OSX : libcudart.dylib, libcudart_static.a, libcudadevrt.a
> Linux : libcudart.so, libcudart_static.a, libcudadevrt.a
> Android : libcudart.so, libcudart_static.a, libcudadevrt.a

**Comment by jolan** [comment]
The Windows CUDA package has contained the dll for a few releases and works ok.

For Linux, I added libcudart.so.8.0 and a "rungominer.sh" script to the v1.0.0 binaries (which are due out any minute):

```bash
#!/bin/sh
LD_LIBRARY_PATH=. ./gominer $@
```

Works ok for me. Will open a docs issue to get that documented.
