### ISSUE TITLE
Validate Paymetheus v1.0.0

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-binaries#42]
Validate paymetheus on x86 and x64:
- [x] Windows 7 x64
- [x] Windows 10 x64

Make sure both icons launch paymetheus correctly.

In the comments note which OS you tested and the results.

**Comment by jcvernaleo** [comment]
Very minimal testing, but installs and runs on win7.

**Comment by tuxcanfly** [comment]
- [x] Windows 10 x64: Installs and runs fine. Obviously needs dcrwallet, dcrd v1.0 for compatibility.

**Comment by jrick** [comment]
A bit late but i did test this on win10
