### ISSUE TITLE
Validate decrediton v1.0.0

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-binaries#43]
Basic testing of the release build needs to be done on supported OSes

- [x] OSX x64
- [x] Linux x64

Testing more than one Linux disto is a good idea so please mention distro or version you tested in comments.

- [ ] Confirm wallet seeds: Create New Seed, receive funds, send funds then recreate with dcrwallet and make sure they are the same.

If there are any other obvious things we need to add here, please add to the issue.

All this testing MUST be done on release builds which will be provided soon.

**Comment by jcvernaleo** [comment]
Looking fine on osx (whichever version I'm running).

**Comment by jcvernaleo** [comment]
Ubuntu 16.04 also

**Comment by jrick** [comment]
A bit late for feedback but i tested around a bit on Fedora 25.  Found plenty of issues but none were deemed worthy of blocking the release and are being looked at.

**Comment by jcvernaleo** [comment]
Since release is done (and this did get done), closing.
