### ISSUE TITLE
Validate dcrinstall v1.0.1

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-binaries#46]
Validate dcrinstall upgrades on the following platforms:
- [x] Linux
- [x] Windows
- [x] OSX

Validate dcrinstall clean install on the following platforms:
- [x] Linux
- [x] Windows
- [x] OSX

**Comment by jcvernaleo** [comment]
Tried clean install and install over v0.8.2 on Ubuntu and both worked.

**Comment by jolan** [comment]
Windows 10:

Upgrade from 1.0.0->1.0.1 OK.
Clean install of 1.0.1 OK.

**Comment by jcvernaleo** [comment]
osx upgrade and clean worked.
