### ISSUE TITLE
Validate Paymetheus v1.0.1

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-binaries#47]
Validate paymetheus on:
- [x] Windows 7 x64
- [ ] Windows 10 x64

Make sure both icons launch paymetheus correctly.

**Comment by jrick** [comment]
Taskbar icon is looking sad for me

![image](https://cloud.githubusercontent.com/assets/1420313/25539534/a8ca1610-2c15-11e7-869d-9c57ce8c3a3b.png)

**Comment by jcvernaleo** [comment]
It is okay on win7

**Comment by jrick** [comment]
Tested again running from vs and the icon looked correct, so it is definitely an MSI issue.

**Comment by jrick** [comment]
Paymetheus installed through the MSI on the left, built locally with VS on the right:

![image](https://cloud.githubusercontent.com/assets/1420313/25540089/d3669536-2c17-11e7-983e-00b4f9c06365.png)

**Comment by jcvernaleo** [comment]
Since I believe it works other than icon graphics issues, we are going with it.
