### ISSUE TITLE
Validate decrediton v1.0.1

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decred-binaries#48]
Basic testing of the release build needs to be done on supported OSes:

- [x] OSX x64
- [x] Linux x64

Testing more than one Linux disto is a good idea so please mention distro or version you tested in comments.

**Comment by jcvernaleo** [comment]
For me, clean and existing both worked (mainnet and testnet) on ubuntu16.04

**Comment by alexlyp** [comment]
OK

**Comment by jcvernaleo** [comment]
tested osx too.
