### ISSUE TITLE
Icon on the taskbar (Windows 10)

### ISSUE THREAD

**Issue by MRGiacalone** [decred/decred-binaries#53]
If I pin Decred to the taskbar it shows a weird looking icon.

Compared to the one for the wallet running it is very different.

![image](https://user-images.githubusercontent.com/7512698/26947219-eb102126-4c5f-11e7-8ba1-ec59f2cd0a97.png)

**Comment by jrick** [comment]
I've seen this as well (it looks broken all the time in my case) but so far I have been the only one to see this behavior.  Thanks for confirming i'm not insane!

Unfortunately i don't know what the actual problem is or how to fix it.

**Comment by jolan** [comment]
1) Paymetheus is now deprecated/unsupported.

2) I have seen this when upgrading Visual Studio Code on Windows 10 when they kept futzing with the icon.  I think it may be a bug in the icon cache.
