### ISSUE TITLE
Missing file for /rpc.cert

### ISSUE THREAD

**Issue by bilalghalib** [decred/decred-binaries#59]
cloudy:decred bilalghalib$ ./dcrctl  --wallet getnewaddress
open /........./Library/Application Support/Dcrwallet/rpc.cert: no such file or directory

Installed CMD line tools, connected using the seed text, can't create new wallet...
Ideas?

**Comment by alexlyp** [comment]
it doesn't generate the rpc.cert until you create the wallet and run it for the first time.

**Comment by bilalghalib** [comment]
Ah, thanks, I see now... although it was searching for the rpc.cert as I
was trying to create the wallet from the command line. Shall I run it with
the GUI first?

On Mon, Sep 25, 2017 at 11:56 PM, Alex Yocom-Piatt <notifications@github.com
