### ISSUE TITLE
Bad link on latest release page

### ISSUE THREAD

**Issue by jgoggan** [decred/decred-binaries#65]
On the releases page: https://github.com/decred/decred-binaries/releases

...the links to download the latest version (v1.1.0) of Paymetheus are broken.  They point to:

https://github.com/decred/decred-binaries/releases/download/v1.0.8/decred_1.1.0-release_x64.msi

...instead of:

https://github.com/decred/decred-binaries/releases/download/v1.1.0/decred_1.1.0-release_x64.msi

(Note that the first version has "v1.0.8" in the path instead of "v1.1.0".)  

People trying to download the latest version will therefore have trouble unless they realize the mistake and manually edit the URL to go to the right location.

Just wanted to let someone know that could fix it.  Thanks.

**Comment by alexlyp** [comment]
Fixed.  But we recommend using Decrediton anyways :)  thanks for the note.

**Comment by jgoggan** [comment]
Sounds good.  I wasn't clear if I should switch to Decrediton either.  I just had Paymetheus before and went to upgrade it.  Might be good to make it clear to recommend the switch if you are using Paymetheus.  Thanks.
