### ISSUE TITLE
add gencerts to package

### ISSUE THREAD

**Issue by logicminds** [decred/decred-binaries#88]
When building from source there are additional utilities that get built during the process.  It was assumed that these utilities would be included in the packages found in this repo.

Example utilities
```
-rwxr-xr-x    1 decred   decred    10191247 Aug 23 22:30 addblock
-rwxr-xr-x    1 decred   decred    11210318 Aug 23 22:30 dcrctl
-rwxr-xr-x    1 decred   decred    18829982 Aug 23 22:31 dcrd
-rwxr-xr-x    1 decred   decred     9961906 Aug 23 22:30 findcheckpoint
-rwxr-xr-x    1 decred   decred     4697431 Aug 23 22:30 gencerts
-rwxr-xr-x    1 decred   decred     1979881 Aug 23 22:30 promptsecret
```

We should ensure that all the utilities are included with the packages hosted here, especially certgen.

**Comment by davecgh** [comment]
I would say the ones we should include are:

- dcrctl
- dcrd
- gencerts
- promptsecret

The others are really developer only.

**Comment by logicminds** [comment]
Currently this is what is distributed ( at least on OS X)

```
-rwxr-xr-x@ 1 decred  staff  11177080 Sep 19 12:08 dcrctl
-rwxr-xr-x@ 1 decred  staff  18715976 Sep 19 12:08 dcrd
-rwxr-xr-x@ 1 decred  staff  22075352 Sep 19 12:09 dcrwallet
-rwxr-xr-x@ 1 decred  staff   2056024 Sep 19 12:08 promptsecret
-rw-r--r--@ 1 decred  staff       908 Sep 19 12:08 sample-dcrctl.conf
-rw-r--r--@ 1 decred  staff      8210 Sep 19 12:09 sample-dcrwallet.conf
```

So looks like gencerts is the only thing needed.
